#!/bin/bash
echo "Adding and commiting files"

# loop for all files until reach to a -m
while [ "$1" != "" ] && [ "$1" != "-m" ]; do
	#Print the file name that is being added
	echo "Adding to staging area $1"
	#Adds the file
	git add "$1"
	#Go to the next parameter
	shift
done
#if theres a -m just shift
if [ "$1" == "-m" ]
then
	shift
fi
#if the last parameter is blank then return a error, else commit with the last parameter as the message
if [ "$1" == "" ]
then
	echo "Error: The commit message is empty, the files where added but no commit will be performed."
else
	git commit -m "$1" && git push -u origin main
fi
